apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins-node
  labels:
    heritage: deis
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: jenkins-node
  template:
    metadata:
      labels:
        app: jenkins-node
    spec:
{{- if .Values.agent.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.agent.nodeSelector | indent 8 }}
{{- end }}
      containers:
        - name: jenkins-node
          image: quay.io/{{.Values.org}}/jenkins-node:{{.Values.docker_tag}}
          imagePullPolicy: Always
          env:
            - name: JENKINS_URL
              value: "{{.Values.jenkins.url}}"
            - name: JENKINS_TUNNEL
              value: "{{.Values.jenkins.tunnel}}"
            - name: JENKINS_NAME
              value: "{{.Values.agent.name}}"
            - name: JENKINS_SECRET
              value: "{{.Values.agent.secret}}"
          volumeMounts:
{{- if .Values.mounts }}
{{ toYaml .Values.mounts | indent 12 }}
{{- end }}
            - name: docker-socket
              mountPath: /var/run/docker.sock
            - name: jenkins-workspace
              mountPath: /home/jenkins/workspace
      volumes:
{{- if .Values.volumes }}
{{ toYaml .Values.volumes | indent 8 }}
{{- end }}
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
        - name: jenkins-workspace
          hostPath:
            path: /home/jenkins/workspace
